name: Build

env:
  BUILD_TYPE: Debug
  VCPKG_ROOT: '${{ github.workspace }}/vcpkg'

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: recursive
    
    - name: Bootstrap vcpkg
      run: |
        cd ${{ env.VCPKG_ROOT }}
        bootstrap-vcpkg.bat

    - name: Integrate vcpkg
      run: |
        cd ${{ env.VCPKG_ROOT }}
        vcpkg.exe integrate install

    - name: Configure CMake
      run: cmake -B ${{ github.workspace }}/build -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} -DDIR_VCPKG_ROOT:PATH="${{ env.VCPKG_ROOT }}" -DVCPKG_MANIFEST_INSTALL:PATH="${{ env.VCPKG_ROOT }}\installed\" -DVCPKG_TARGET_TRIPLET:STRING="${{ env.arch }}-windows-static" -DCMAKE_TOOLCHAIN_FILE:PATH="${{ env.VCPKG_ROOT }}\scripts\buildsystems\vcpkg.cmake" -Wno-dev

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}


